# Generated by Django 4.0.1 on 2022-02-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'food_list',
            },
        ),
        migrations.CreateModel(
            name='recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
        migrations.CreateModel(
            name='wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
                ('vintage', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=256)),
                ('rating', models.IntegerField()),
                ('price', models.IntegerField(null=True)),
                ('primary_flavors', models.TextField(null=True)),
                ('chefs_note', models.TextField(null=True)),
            ],
            options={
                'db_table': 'wine_list',
            },
        ),
        migrations.CreateModel(
            name='wineTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.IntegerField()),
                ('tannin', models.IntegerField()),
                ('acidity', models.IntegerField()),
                ('sweetness', models.IntegerField()),
            ],
            options={
                'db_table': 'wine_taste',
            },
        ),
    ]
