# Generated by Django 4.0.1 on 2022-02-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
                ('vintage', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=256)),
                ('rating', models.IntegerField()),
                ('price', models.IntegerField(null=True)),
                ('primary_flavors', models.TextField(null=True)),
                ('food', models.ManyToManyField(blank=True, to='recommendation.Food')),
            ],
            options={
                'db_table': 'wine',
            },
        ),
        migrations.CreateModel(
            name='WineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.IntegerField()),
                ('tannin', models.IntegerField()),
                ('acidity', models.IntegerField()),
                ('sweetness', models.IntegerField()),
                ('wine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommendation.wine')),
            ],
            options={
                'db_table': 'wine_profile',
            },
        ),
    ]
