# Generated by Django 4.0.1 on 2022-02-08 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winerecommend',
            name='user',
            field=models.ForeignKey(limit_choices_to={'surveyed': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='winerecommend',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.wine'),
        ),
        migrations.AddField(
            model_name='wineprofile',
            name='wine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recommendation.wine'),
        ),
        migrations.AddField(
            model_name='winefood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.food'),
        ),
        migrations.AddField(
            model_name='winefood',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.wine'),
        ),
        migrations.AddField(
            model_name='wine',
            name='mypic',
            field=models.ManyToManyField(blank=True, related_name='my_pic', to=settings.AUTH_USER_MODEL),
        ),
    ]
