# Generated by Django 4.0.1 on 2022-02-08 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='item',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='item',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='vintage',
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='mypic',
            field=models.ManyToManyField(blank=True, related_name='my_pic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wine',
            name='purchase_link',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='saved_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='food',
            field=models.ManyToManyField(blank=True, related_name='food_for_wine', to='recommendation.Food'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='primary_flavors',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wineprofile',
            name='acidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wineprofile',
            name='body',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wineprofile',
            name='sweetness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wineprofile',
            name='tannin',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='WineRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(limit_choices_to={'surveyed': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.wine')),
            ],
            options={
                'db_table': 'user_recommend',
            },
        ),
    ]
