# Generated by Django 4.0.2 on 2022-02-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_wine_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='national_flag',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
