# Generated by Django 4.0.1 on 2022-02-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_rename_item_food_name_rename_item_wine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.CharField(default=' ', max_length=512),
            preserve_default=False,
        ),
    ]
