# Generated by Django 4.0.1 on 2022-02-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='ytinfo',
            field=models.TextField(null=True),
        ),
    ]
