# Generated by Django 4.0.1 on 2022-02-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_wine_ytinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='yturl',
            field=models.URLField(max_length=256, null=True),
        ),
    ]
